### ISSUE TITLE
Searcher not invokes when input includes underscore(_), the number followed by underscore

### ISSUE THREAD

**Issue by myname-gokul** [alireza-sohrabi/ngx-mat-select#1]
**Describe the bug**
The searcher funtion invokes in normal condition, but not when search input contains underscore(_)

**To Reproduce**
give input 'bank_0' in searchbox, you will not see refeshing, and same result as of bank

**Expected behavior**
'bank_0' input should return only the item with value 'bank_0'

**Screenshots**
![image](https://user-images.githubusercontent.com/88393725/128048845-be24ed54-4358-457f-9eab-c7759bcde3f1.png)

**Comment by alireza-sohrabi** [comment]
Hi, thanks for debugging. I will fix that in next version
